/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */
package net.atomique.ksar.ui

import net.atomique.ksar.VersionNumber
import org.slf4j.LoggerFactory
import java.awt.Cursor
import java.awt.Desktop
import java.awt.Frame
import java.awt.event.ActionEvent
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.io.IOException
import java.net.URI
import java.net.URISyntaxException
import javax.swing.JLabel

class AboutBox
/**
 * Creates new form AboutBox
 */
    (parent: Frame?) : javax.swing.JDialog(parent) {

    init {
        initComponents()
        setLocationRelativeTo(parent)
        isModal = true
        isVisible = true
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        jPanel3 = javax.swing.JPanel()
        versionlabel = javax.swing.JLabel()
        jPanel2 = javax.swing.JPanel()
        urllabel = javax.swing.JLabel()
        authorlabel = javax.swing.JLabel()
        licencelabel = javax.swing.JLabel()
        tipslabel = javax.swing.JLabel()
        jPanel1 = javax.swing.JPanel()
        OkButton = javax.swing.JButton()

        defaultCloseOperation = javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE
        contentPane.layout =
            javax.swing.BoxLayout(contentPane, javax.swing.BoxLayout.PAGE_AXIS)

        jPanel3.border = javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)

        versionlabel.text = "kSar version: " + VersionNumber.versionString

        val jPanel3Layout = javax.swing.GroupLayout(jPanel3)
        jPanel3.layout = jPanel3Layout
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 357, Short.MAX_VALUE.toInt())
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 118, Short.MAX_VALUE.toInt())
                        .addComponent(versionlabel)
                        .addGap(0, 119, Short.MAX_VALUE.toInt())))
        )
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 16, Short.MAX_VALUE.toInt())
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE.toInt())
                        .addComponent(versionlabel)
                        .addGap(0, 0, Short.MAX_VALUE.toInt())))
        )

        contentPane.add(jPanel3)

        jPanel2.layout = javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS)

        var url = "https://github.com/vlsi/ksar"
        urllabel.text = String.format("<html>Website: <a href=\"%s\">%s</a></html>", url, url)
        urllabel.cursor = Cursor(Cursor.HAND_CURSOR)
        jPanel2.add(urllabel)
        openInBrowser(urllabel, url)

        // Pin the contributors link to the running release so it keeps pointing at the file as it
        // was for this version. Development (SNAPSHOT) builds have no matching tag, so fall back to
        // the default branch.
        val version = VersionNumber.versionString
        val ref = if (version.endsWith("-SNAPSHOT")) "master" else "v$version"
        url = "https://github.com/vlsi/ksar/blob/$ref/CONTRIBUTORS.md"
        authorlabel.text =
            String.format("<html>Authors: <a href=\"%s\">CONTRIBUTORS.md</a></html>", url)
        authorlabel.cursor = Cursor(Cursor.HAND_CURSOR)
        jPanel2.add(authorlabel)
        openInBrowser(authorlabel, url)

        licencelabel.text = "License: BSD-3-Clause (see LICENSE file)"
        jPanel2.add(licencelabel)

        url = "https://sourceforge.net/projects/ksar/"
        tipslabel.text = String.format("<html>Fork of: <a href=\"%s\">%s</a></html>", url, url)
        tipslabel.cursor = Cursor(Cursor.HAND_CURSOR)
        jPanel2.add(tipslabel)
        openInBrowser(tipslabel, url)

        contentPane.add(jPanel2)

        OkButton.text = "Ok"
        OkButton.addActionListener { evt -> OkButtonActionPerformed(evt) }
        jPanel1.add(OkButton)

        contentPane.add(jPanel1)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun OkButtonActionPerformed(
        evt: ActionEvent?
    ) { //GEN-FIRST:event_OkButtonActionPerformed
        isVisible = false
        dispose()
    } //GEN-LAST:event_OkButtonActionPerformed

    private fun openInBrowser(label: JLabel, url: String) {
        label.addMouseListener(object : MouseAdapter() {
            override fun mouseClicked(e: MouseEvent) {
                if (!Desktop.isDesktopSupported()
                    || !Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)
                ) {
                    log.warn("Desktop browsing is unavailable; cannot open {}", url)
                    return
                }
                try {
                    Desktop.getDesktop().browse(URI(url))
                } catch (ex: IOException) {
                    log.warn("Unable to open {} in a browser", url, ex)
                } catch (ex: URISyntaxException) {
                    log.warn("Unable to open {} in a browser", url, ex)
                }
            }
        })
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var OkButton: javax.swing.JButton
    private lateinit var authorlabel: javax.swing.JLabel
    private lateinit var jPanel1: javax.swing.JPanel
    private lateinit var jPanel2: javax.swing.JPanel
    private lateinit var jPanel3: javax.swing.JPanel
    private lateinit var licencelabel: javax.swing.JLabel
    private lateinit var tipslabel: javax.swing.JLabel
    private lateinit var urllabel: javax.swing.JLabel
    private lateinit var versionlabel: javax.swing.JLabel
    // End of variables declaration//GEN-END:variables

    companion object {
        private val log = LoggerFactory.getLogger(AboutBox::class.java)
    }
}
