/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */

package net.atomique.ksar.ui

import net.atomique.ksar.Config
import net.atomique.ksar.GlobalOptions
import net.atomique.ksar.export.FileCSV
import net.atomique.ksar.export.FilePDF
import net.atomique.ksar.graph.Graph
import net.atomique.ksar.graph.List
import net.atomique.ksar.kSar
import org.slf4j.LoggerFactory

import java.io.File
import javax.swing.JCheckBox
import javax.swing.JDialog
import javax.swing.JFileChooser
import javax.swing.JFrame
import javax.swing.JLabel
import javax.swing.JOptionPane
import javax.swing.JPanel
import javax.swing.JProgressBar
import javax.swing.tree.DefaultTreeModel
import javax.swing.tree.TreePath

class DataView
/**
 * Creates new form DataView
 */
    (sar: kSar) : javax.swing.JInternalFrame() {

    private val mysar: kSar

    init {
        initComponents()
        mysar = sar
        jTree1.model = DefaultTreeModel(mysar.graphtree)
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        jPanel1 = javax.swing.JPanel()
        jSplitPane1 = javax.swing.JSplitPane()
        jPanel2 = javax.swing.JPanel()
        jScrollPane1 = javax.swing.JScrollPane()
        jTree1 = javax.swing.JTree()
        jButton1 = javax.swing.JButton()
        displayPanel = javax.swing.JPanel()
        jMenuBar1 = javax.swing.JMenuBar()
        dataMenu = javax.swing.JMenu()
        LoadFile = javax.swing.JMenuItem()
        LoadCommand = javax.swing.JMenuItem()
        LoadSSH = javax.swing.JMenuItem()
        GraphMenu = javax.swing.JMenu()
        addgraphMenu = javax.swing.JMenuItem()
        exportMenu = javax.swing.JMenu()
        PDFMenu = javax.swing.JMenuItem()
        CSVMenu = javax.swing.JMenuItem()

        setClosable(true)
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE)
        setIconifiable(true)
        setMaximizable(true)
        setResizable(true)
        try {
            setSelected(true)
        } catch (e1: java.beans.PropertyVetoException) {
            e1.printStackTrace()
        }
        isVisible = true
        addInternalFrameListener(object : javax.swing.event.InternalFrameListener {
            override fun internalFrameOpened(evt: javax.swing.event.InternalFrameEvent) {
            }

            override fun internalFrameClosing(evt: javax.swing.event.InternalFrameEvent) {
                formInternalFrameClosing(evt)
            }

            override fun internalFrameClosed(evt: javax.swing.event.InternalFrameEvent) {
            }

            override fun internalFrameIconified(evt: javax.swing.event.InternalFrameEvent) {
            }

            override fun internalFrameDeiconified(evt: javax.swing.event.InternalFrameEvent) {
            }

            override fun internalFrameActivated(evt: javax.swing.event.InternalFrameEvent) {
            }

            override fun internalFrameDeactivated(evt: javax.swing.event.InternalFrameEvent) {
            }
        })

        jPanel1.layout = java.awt.BorderLayout()

        jPanel2.minimumSize = java.awt.Dimension(150, 46)
        jPanel2.layout = java.awt.BorderLayout()

        jTree1.addTreeSelectionListener { evt -> jTree1ValueChanged(evt) }
        jScrollPane1.setViewportView(jTree1)

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER)

        jButton1.isEnabled = false
        jButton1.addActionListener { evt -> jButton1ActionPerformed(evt) }
        jPanel2.add(jButton1, java.awt.BorderLayout.SOUTH)

        jSplitPane1.leftComponent = jPanel2

        displayPanel.layout = java.awt.BorderLayout()
        jSplitPane1.rightComponent = displayPanel

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER)

        contentPane.add(jPanel1, java.awt.BorderLayout.CENTER)

        dataMenu.text = "Data"

        LoadFile.text = "Load from a file..."
        LoadFile.addActionListener { evt -> LoadFileActionPerformed(evt) }
        dataMenu.add(LoadFile)

        LoadCommand.text = "Load from a local Command..."
        LoadCommand.addActionListener { evt -> LoadCommandActionPerformed(evt) }
        dataMenu.add(LoadCommand)

        LoadSSH.text = "Load from a SSH Command..."
        LoadSSH.addActionListener { evt -> LoadSSHActionPerformed(evt) }
        dataMenu.add(LoadSSH)

        jMenuBar1.add(dataMenu)

        GraphMenu.text = "Graph"
        GraphMenu.isEnabled = false

        addgraphMenu.text = "Add a Graph"
        addgraphMenu.addActionListener { evt -> addgraphMenuActionPerformed(evt) }
        GraphMenu.add(addgraphMenu)

        jMenuBar1.add(GraphMenu)

        exportMenu.text = "Export"
        exportMenu.isEnabled = false

        PDFMenu.text = "Export to PDF..."
        PDFMenu.addActionListener { evt -> PDFMenuActionPerformed(evt) }
        exportMenu.add(PDFMenu)

        CSVMenu.text = "Export to CSV..."
        CSVMenu.addActionListener { evt -> CSVMenuActionPerformed(evt) }
        exportMenu.add(CSVMenu)

        jMenuBar1.add(exportMenu)

        setJMenuBar(jMenuBar1)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun formInternalFrameClosing(
        evt: javax.swing.event.InternalFrameEvent
    ) { //GEN-FIRST:event_formInternalFrameClosing
        save_data()
        dispose()
    } //GEN-LAST:event_formInternalFrameClosing

    private fun jTree1ValueChanged(
        evt: javax.swing.event.TreeSelectionEvent
    ) { //GEN-FIRST:event_jTree1ValueChanged
        val treepath: TreePath = evt.path
        val obj: Any? = treepath.lastPathComponent
        if (obj != null) {

            log.trace("mem: {}", Runtime.getRuntime().totalMemory())
            log.trace("free: {}", Runtime.getRuntime().freeMemory())

            val treenode = obj as SortedTreeNode
            if (treenode.root === treenode) {
                if (current_panel != null) {
                    displayPanel.removeAll()
                    current_panel = null
                }
                displayPanel.repaint()
            }
            val obj1: Any? = treenode.userObject
            if (obj1 is TreeNodeInfo) {
                val tmpnode: TreeNodeInfo = obj1
                val nodeobj: Graph = tmpnode.node_object
                if (current_panel != null) {
                    displayPanel.removeAll()
                    current_panel = null
                }
                mygraphview.setGraph(nodeobj)
                current_panel = mygraphview
                displayPanel.add(mygraphview)
                displayPanel.validate()
                displayPanel.repaint()

            }
            if (obj1 is ParentNodeInfo) {
                val tmpnode: ParentNodeInfo = obj1
                val nodeobj: List = tmpnode.node_object
                if (current_panel != null) {
                    displayPanel.removeAll()
                    current_panel = null
                }
                current_panel = nodeobj.run()
                displayPanel.add(current_panel)
                displayPanel.validate()
                displayPanel.repaint()
            }
        }

    } //GEN-LAST:event_jTree1ValueChanged

    private fun LoadCommandActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_LoadCommandActionPerformed
        mysar.do_localcommand(null)
    } //GEN-LAST:event_LoadCommandActionPerformed

    private fun LoadFileActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_LoadFileActionPerformed
        mysar.do_fileread(null)

    } //GEN-LAST:event_LoadFileActionPerformed

    private fun LoadSSHActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_LoadSSHActionPerformed
        mysar.do_sshread(null)
    } //GEN-LAST:event_LoadSSHActionPerformed

    private fun PDFMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_PDFMenuActionPerformed
        var tmp: GraphSelection? = GraphSelection(GlobalOptions.uI, true, this)
        ask_treenode(mysar.graphtree, tmp!!)
        tmp.isVisible = true
        if (!tmp.OkforExport) {
            tmp = null
            return
        }
        tmp = null
        val filename = askSaveFilename("Export PDF", Config.getLastExportDirectory()) ?: return
        Config.setLastExportDirectory(filename)
        if (!Config.getLastExportDirectory()!!.isDirectory) {
            Config.setLastExportDirectory(Config.getLastExportDirectory()!!.parentFile)
            Config.save()
        }
        doExportPDF(filename)
    } //GEN-LAST:event_PDFMenuActionPerformed

    private fun CSVMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_CSVMenuActionPerformed
        val tmp = GraphSelection(GlobalOptions.uI, true, this)
        ask_treenode(mysar.graphtree, tmp)
        tmp.isVisible = true
        if (!tmp.OkforExport) {
            return

        }
        val filename = askSaveFilename("Export CSV", Config.getLastExportDirectory()) ?: return
        Config.setLastExportDirectory(filename)
        if (!Config.getLastExportDirectory()!!.isDirectory) {
            Config.setLastExportDirectory(Config.getLastExportDirectory()!!.parentFile)
            Config.save()
        }
        doExportCSV(filename)
    } //GEN-LAST:event_CSVMenuActionPerformed

    private fun addgraphMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_addgraphMenuActionPerformed
        // TODO add your handling code here:

    } //GEN-LAST:event_addgraphMenuActionPerformed

    private fun jButton1ActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_jButton1ActionPerformed
        mysar.interrupt_parsing()
        jButton1.text = ""
    } //GEN-LAST:event_jButton1ActionPerformed

    private fun askSaveFilename(title: String, chdirto: File?): String? {
        var filename: String? = null
        val chooser = JFileChooser()
        chooser.dialogTitle = title
        if (chdirto != null) {
            chooser.currentDirectory = chdirto
        }
        val returnVal = chooser.showSaveDialog(GlobalOptions.uI)
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            filename = chooser.selectedFile.absolutePath
        }

        if (filename == null) {
            return null
        }

        if (File(filename).exists()) {
            val choix = arrayOf("Yes", "No")
            val resultat =
                JOptionPane.showOptionDialog(
                    null, "Overwrite $filename ?", "File Exist",
                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, choix,
                    choix[1]
                )
            if (resultat != 0) {
                return null
            }
        }
        return filename
    }

    fun doExportPDF(filename: String) {
        var pages = 0
        pages = mysar.get_page_to_print()
        val panel0 = JPanel()
        val panel1 = JPanel()
        val panel2 = JPanel()
        val pbar = JProgressBar()
        pbar.minimum = 0
        pbar.maximum = pages
        pbar.isStringPainted = true
        val mytitre = JLabel("Exporting: ")
        panel1.add(mytitre)
        panel2.add(pbar)
        panel0.add(panel1)
        panel0.add(panel2)
        val mydial = JDialog()
        mydial.defaultCloseOperation = JFrame.DISPOSE_ON_CLOSE
        mydial.contentPane = panel0
        mydial.setSize(250, 80)
        mydial.pack()
        mydial.setLocationRelativeTo(GlobalOptions.uI)
        mydial.isVisible = true

        val t: Runnable = FilePDF(filename, mysar, pbar, mydial)
        val th = Thread(t)
        th.start()

    }

    fun doExportCSV(filename: String) {
        var pages = 0
        pages = mysar.myparser.dateSamples.size
        val panel0 = JPanel()
        val panel1 = JPanel()
        val panel2 = JPanel()
        val pbar = JProgressBar()
        pbar.minimum = 0
        pbar.maximum = pages
        pbar.isStringPainted = true
        val mytitre = JLabel("Exporting: ")
        panel1.add(mytitre)
        panel2.add(pbar)
        panel0.add(panel1)
        panel0.add(panel2)
        val mydial = JDialog()
        mydial.defaultCloseOperation = JFrame.DISPOSE_ON_CLOSE
        mydial.contentPane = panel0
        mydial.setSize(250, 80)
        mydial.pack()
        mydial.setLocationRelativeTo(GlobalOptions.uI)
        mydial.isVisible = true

        val t: Runnable = FileCSV(filename, mysar, pbar, mydial)
        val th = Thread(t)
        th.start()

    }


    fun ask_treenode(node: SortedTreeNode, graphselection: GraphSelection) {
        val num = node.childCount

        if (num > 0) {
            val obj1: Any? = node.userObject
            if (obj1 is ParentNodeInfo) {
                val tmpnode: ParentNodeInfo = obj1
                val nodeobj: List = tmpnode.node_object
                askparentPanel = nodeobj.getprintform()
                graphselection.addPrintCheckBox(askparentPanel!!)
            }
            for (i in 0 until num) {
                val l = node.getChildAt(i) as SortedTreeNode
                ask_treenode(l, graphselection)
            }
            askparentPanel = null
        } else {
            val obj1: Any? = node.userObject
            if (obj1 is TreeNodeInfo) {
                val tmpnode: TreeNodeInfo = obj1
                val nodeobj: Graph = tmpnode.node_object
                val tmp: JCheckBox = nodeobj.getprintform()
                val askparentPanelLocal = askparentPanel
                if (askparentPanelLocal == null) {
                    graphselection.addPrintCheckBox(tmp)
                } else {
                    askparentPanelLocal.add(tmp)
                }
            }
        }
    }

    fun add2tree(parent: SortedTreeNode, newNode: SortedTreeNode) {
        val model = jTree1.model as DefaultTreeModel
        model.insertNodeInto(newNode, parent, parent.childCount)
        /*if( newNode.getUserObject() instanceof TreeNodeInfo ) {
      model.reload();
    }*/
    }

    fun treehome() {
        jTree1.setSelectionRow(0)
        jTree1.expandRow(0)
        jTree1.repaint()
    }

    fun notifyrun(t: Boolean) {
        exportMenu.isEnabled = !t
        dataMenu.isEnabled = !t
        if (t) {
            jButton1.text = "Stop"
            jButton1.isEnabled = true
        } else {
            jButton1.text = ""
            jButton1.isEnabled = false
        }
    }

    fun setHasData(actif: Boolean) {
        has_fresh_data = actif
        exportMenu.isEnabled = actif
        if (actif) {
            LoadFile.text = "Append from a file..."
            LoadCommand.text = "Append from a local Command..."
            LoadSSH.text = "Append from a SSH Command..."
        } else {
            LoadFile.text = "Load from a file..."
            LoadCommand.text = "Load from a local Command..."
            LoadSSH.text = "Load from a SSH Command..."
        }
    }

    private fun save_data() {
        if (has_fresh_data) {
            log.info("need backup")
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var CSVMenu: javax.swing.JMenuItem
    private lateinit var GraphMenu: javax.swing.JMenu
    private lateinit var LoadCommand: javax.swing.JMenuItem
    private lateinit var LoadFile: javax.swing.JMenuItem
    private lateinit var LoadSSH: javax.swing.JMenuItem
    private lateinit var PDFMenu: javax.swing.JMenuItem
    private lateinit var addgraphMenu: javax.swing.JMenuItem
    private lateinit var dataMenu: javax.swing.JMenu
    private lateinit var displayPanel: javax.swing.JPanel
    private lateinit var exportMenu: javax.swing.JMenu
    private lateinit var jButton1: javax.swing.JButton
    private lateinit var jMenuBar1: javax.swing.JMenuBar
    private lateinit var jPanel1: javax.swing.JPanel
    private lateinit var jPanel2: javax.swing.JPanel
    private lateinit var jScrollPane1: javax.swing.JScrollPane
    private lateinit var jSplitPane1: javax.swing.JSplitPane
    private lateinit var jTree1: javax.swing.JTree
    // End of variables declaration//GEN-END:variables
    private var has_fresh_data = false
    private var current_panel: JPanel? = null
    private val mygraphview = GraphView()
    private var askparentPanel: JPanel? = null
    private val total_graph = 0

    companion object {
        private val log = LoggerFactory.getLogger(DataView::class.java)
    }
}
