/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */
package net.atomique.ksar.ui

import net.atomique.ksar.kSar
import org.slf4j.LoggerFactory
import java.awt.GraphicsEnvironment
import java.awt.Rectangle
import java.beans.PropertyVetoException
import javax.swing.JDesktopPane
import javax.swing.JInternalFrame
import javax.swing.JOptionPane

class Desktop : javax.swing.JFrame() {

    /**
     * Creates new form Desktop
     */
    init {
        val wmargins = 90
        val hmargins = 60
        var desktopBounds = Rectangle()

        val ge = GraphicsEnvironment.getLocalGraphicsEnvironment()
        val gs = ge.screenDevices

        //get configuration from all screens for tracing
        for (j in gs.indices) {
            val gd = gs[j]
            val gc = gd.defaultConfiguration

            val screenBounds = gc.bounds
            log.debug("screen [{}] boundaries: {}", j, screenBounds.toString())

            //use screen0 boundaries for Desktop placement
            if (j == 0) {
                desktopBounds = screenBounds
                desktopBounds.x += wmargins
                desktopBounds.y += hmargins
                desktopBounds.width -= (wmargins * 2)
                desktopBounds.height -= (hmargins * 2)
            }
        }

        initComponents()

        bounds = desktopBounds
        log.debug("desktop window boundaries: {}", this.bounds.toString())

        DesktopPane.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE)
        isVisible = true
    }

    fun maxall() {
        maximize(DesktopPane)
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        DesktopPane = javax.swing.JDesktopPane()
        MenuBar = javax.swing.JMenuBar()
        FileMenu = javax.swing.JMenu()
        NewMenu = javax.swing.JMenuItem()
        QuitMenu = javax.swing.JMenuItem()
        OptionsMenu = javax.swing.JMenu()
        SysprefMenu = javax.swing.JMenuItem()
        WindowMenu = javax.swing.JMenu()
        TileMenu = javax.swing.JMenuItem()
        IconifyMenu = javax.swing.JMenuItem()
        MaximizeMenu = javax.swing.JMenuItem()
        HelpMenu = javax.swing.JMenu()
        AboutMenu = javax.swing.JMenuItem()

        defaultCloseOperation = javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE
        title = "kSar : a sar grapher"
        addWindowListener(object : java.awt.event.WindowAdapter() {
            override fun windowClosing(evt: java.awt.event.WindowEvent) {
                formWindowClosing(evt)
            }
        })
        contentPane.add(DesktopPane, java.awt.BorderLayout.CENTER)

        FileMenu.text = "File" // NOI18N

        NewMenu.text = "New window"
        NewMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                NewMenuActionPerformed(evt)
            }
        })
        FileMenu.add(NewMenu)

        QuitMenu.text = "Quit"
        QuitMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                QuitMenuActionPerformed(evt)
            }
        })
        FileMenu.add(QuitMenu)

        MenuBar.add(FileMenu)

        OptionsMenu.text = "Options" // NOI18N

        SysprefMenu.text = "System Preferences"
        SysprefMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                SysprefMenuActionPerformed(evt)
            }
        })
        OptionsMenu.add(SysprefMenu)

        MenuBar.add(OptionsMenu)

        WindowMenu.text = "Window"

        TileMenu.text = "Tile"
        TileMenu.actionCommand = "TileMenu"
        TileMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                TileMenuActionPerformed(evt)
            }
        })
        WindowMenu.add(TileMenu)

        IconifyMenu.text = "Iconify"
        IconifyMenu.actionCommand = "IconifyMenu"
        IconifyMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                IconifyMenuActionPerformed(evt)
            }
        })
        WindowMenu.add(IconifyMenu)

        MaximizeMenu.text = "Maximize"
        MaximizeMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                MaximizeMenuActionPerformed(evt)
            }
        })
        WindowMenu.add(MaximizeMenu)

        MenuBar.add(WindowMenu)

        HelpMenu.text = "?"

        AboutMenu.text = "About"
        AboutMenu.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                AboutMenuActionPerformed(evt)
            }
        })
        HelpMenu.add(AboutMenu)

        MenuBar.add(HelpMenu)

        jMenuBar = MenuBar

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun formWindowClosing(
        evt: java.awt.event.WindowEvent
    ) { //GEN-FIRST:event_formWindowClosing
        tryToQuit()
    } //GEN-LAST:event_formWindowClosing

    private fun QuitMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_QuitMenuActionPerformed
        tryToQuit()
    } //GEN-LAST:event_QuitMenuActionPerformed

    private fun AboutMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_AboutMenuActionPerformed
        val myAboutBox = AboutBox(this)
    } //GEN-LAST:event_AboutMenuActionPerformed

    private fun SysprefMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_SysprefMenuActionPerformed
        val myPreferences = Preferences(this)
    } //GEN-LAST:event_SysprefMenuActionPerformed

    private fun NewMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_NewMenuActionPerformed
        add_window()
    } //GEN-LAST:event_NewMenuActionPerformed

    private fun TileMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_TileMenuActionPerformed
        tile(DesktopPane)
    } //GEN-LAST:event_TileMenuActionPerformed

    private fun IconifyMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_IconifyMenuActionPerformed
        iconify(DesktopPane)
    } //GEN-LAST:event_IconifyMenuActionPerformed

    private fun MaximizeMenuActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_MaximizeMenuActionPerformed
        maximize(DesktopPane)
    } //GEN-LAST:event_MaximizeMenuActionPerformed

    fun add_window() {
        val mysar = kSar(DesktopPane)
    }

    fun getDesktopPane(): JDesktopPane {
        return DesktopPane
    }

    private fun tryToQuit() {
        val i = JOptionPane.showConfirmDialog(
            this, "Are you sure you want to exit kSar ?", "Confirm",
            JOptionPane.YES_NO_OPTION
        )
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0)
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var AboutMenu: javax.swing.JMenuItem
    private lateinit var DesktopPane: javax.swing.JDesktopPane
    private lateinit var FileMenu: javax.swing.JMenu
    private lateinit var HelpMenu: javax.swing.JMenu
    private lateinit var IconifyMenu: javax.swing.JMenuItem
    private lateinit var MaximizeMenu: javax.swing.JMenuItem
    private lateinit var MenuBar: javax.swing.JMenuBar
    private lateinit var NewMenu: javax.swing.JMenuItem
    private lateinit var OptionsMenu: javax.swing.JMenu
    private lateinit var QuitMenu: javax.swing.JMenuItem
    private lateinit var SysprefMenu: javax.swing.JMenuItem
    private lateinit var TileMenu: javax.swing.JMenuItem
    private lateinit var WindowMenu: javax.swing.JMenu
    // End of variables declaration//GEN-END:variables

    companion object {
        private val log = LoggerFactory.getLogger(Desktop::class.java)

        private fun filterFrame(frames: Array<JInternalFrame>): Array<JInternalFrame> {
            var n = 0
            for (i in frames.indices) {
                if (frames[i].isVisible && !frames[i].isIcon) {
                    n++
                }
            }

            val newfs = arrayOfNulls<JInternalFrame>(n)
            var j = 0
            for (i in frames.indices) {
                if (frames[i].isVisible && !frames[i].isIcon) {
                    newfs[j++] = frames[i]
                }
            }
            @Suppress("UNCHECKED_CAST")
            return newfs as Array<JInternalFrame>
        }

        fun iconify(desktopPane: JDesktopPane) {
            val frames = filterFrame(desktopPane.allFrames)
            if (frames.isEmpty()) {
                return
            }
            for (i in frames.indices) {
                if (frames[i].isVisible && !frames[i].isIcon) {
                    try {
                        frames[i].setIcon(true)
                    } catch (ex: PropertyVetoException) {
                        log.error("PropertyVetoException", ex)
                    }
                }
            }
        }

        private fun maximize(desktopPane: JDesktopPane) {
            val frames = filterFrame(desktopPane.allFrames)
            if (frames.isEmpty()) {
                return
            }
            for (i in frames.indices) {
                if (frames[i].isVisible && !frames[i].isIcon) {
                    try {
                        frames[i].setMaximum(true)
                    } catch (ex: PropertyVetoException) {
                        log.error("PropertyVetoException", ex)
                    }
                }
            }
        }

        fun tile(desktopPane: JDesktopPane) {
            val frames = filterFrame(desktopPane.allFrames)
            if (frames.isEmpty()) {
                return
            }

            tile(frames, desktopPane.bounds)
        }

        private fun tile(frames: Array<JInternalFrame>, dBounds: Rectangle) {
            val cols = Math.sqrt(frames.size.toDouble()).toInt()
            var rows = Math.ceil(frames.size.toDouble() / cols).toInt()
            val lastRow = frames.size - cols * (rows - 1)
            var width: Int
            val height: Int

            if (lastRow == 0) {
                rows--
                height = dBounds.height / rows
            } else {
                height = dBounds.height / rows
                if (lastRow < cols) {
                    rows--
                    width = dBounds.width / lastRow
                    for (i in 0 until lastRow) {
                        frames[cols * rows + i].setBounds(i * width, rows * height, width, height)
                    }
                }
            }

            width = dBounds.width / cols
            for (j in 0 until rows) {
                for (i in 0 until cols) {
                    frames[i + j * cols].setBounds(i * width, j * height, width, height)
                }
            }
        }
    }
}
