/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */

package net.atomique.ksar.ui

import net.atomique.ksar.Config
import net.atomique.ksar.GlobalOptions
import net.atomique.ksar.graph.Graph
import org.jfree.chart.ChartPanel
import org.slf4j.LoggerFactory

import java.io.BufferedWriter
import java.io.File
import java.io.FileWriter
import java.io.IOException
import javax.swing.JFileChooser
import javax.swing.JOptionPane

class GraphView
/**
 * Creates new form GraphView
 */
    : javax.swing.JPanel() {

    init {
        initComponents()
    }

    fun setGraph(graph: Graph) {
        this.thegraph = graph
        if (mychartpanel != null) {
            graphPanel.remove(mychartpanel)
        }
        mychartpanel = graph.getChartPanel()
        graphPanel.add(mychartpanel)
        this.validate()
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        graphPanel = javax.swing.JPanel()
        buttonPanel = javax.swing.JPanel()
        csvButton = javax.swing.JButton()
        jpgBuitton = javax.swing.JButton()
        pngButton = javax.swing.JButton()
        ctrlcButton = javax.swing.JButton()
        printButton = javax.swing.JButton()

        layout = java.awt.BorderLayout()

        graphPanel.layout = java.awt.BorderLayout()
        add(graphPanel, java.awt.BorderLayout.CENTER)

        csvButton.text = "Export CSV"
        csvButton.addActionListener { evt -> csvButtonActionPerformed(evt) }
        buttonPanel.add(csvButton)

        jpgBuitton.text = "Export JPG"
        jpgBuitton.addActionListener { evt -> jpgBuittonActionPerformed(evt) }
        buttonPanel.add(jpgBuitton)

        pngButton.text = "Export PNG"
        pngButton.addActionListener { evt -> pngButtonActionPerformed(evt) }
        buttonPanel.add(pngButton)

        ctrlcButton.text = "Copy"
        ctrlcButton.addActionListener { evt -> ctrlcButtonActionPerformed(evt) }
        buttonPanel.add(ctrlcButton)

        printButton.text = "Print"
        printButton.addActionListener { evt -> printButtonActionPerformed(evt) }
        buttonPanel.add(printButton)

        add(buttonPanel, java.awt.BorderLayout.SOUTH)
    } // </editor-fold>//GEN-END:initComponents

    private fun csvButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_csvButtonActionPerformed
        val filename: String?
        val buffer: String

        filename = askSaveFilename("Export CSV", Config.getLastExportDirectory())

        if (filename == null) {
            return
        }
        Config.setLastExportDirectory(filename)
        if (!Config.getLastExportDirectory()!!.isDirectory) {
            Config.setLastExportDirectory(Config.getLastExportDirectory()!!.parentFile)
            Config.save()
        }

        buffer = thegraph!!.make_csv()

        log.debug(buffer)

        var out: BufferedWriter?
        try {
            out = BufferedWriter(FileWriter(filename))
        } catch (e: IOException) {
            out = null
        }
        if (out == null) {
            return
        }
        try {
            out.write(buffer)
            out.flush()
            out.close()
        } catch (e: IOException) {

        }


    } //GEN-LAST:event_csvButtonActionPerformed

    private fun jpgBuittonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_jpgBuittonActionPerformed
        val filename = askSaveFilename("Export JPG", Config.getLastExportDirectory())
        if (filename == null) {
            return
        }
        thegraph!!.saveJPG(filename, Config.imageWidth, Config.imageHeight)
    } //GEN-LAST:event_jpgBuittonActionPerformed

    private fun ctrlcButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_ctrlcButtonActionPerformed
        mychartpanel!!.doCopy()
    } //GEN-LAST:event_ctrlcButtonActionPerformed

    private fun printButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_printButtonActionPerformed
        mychartpanel!!.createChartPrintJob()
    } //GEN-LAST:event_printButtonActionPerformed

    private fun pngButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_pngButtonActionPerformed
        val filename = askSaveFilename("Export PNG", Config.getLastExportDirectory())
        if (filename == null) {
            return
        }
        thegraph!!.savePNG(filename, Config.imageWidth, Config.imageHeight)
    } //GEN-LAST:event_pngButtonActionPerformed


    private fun askSaveFilename(title: String, chdirto: File?): String? {
        var filename: String? = null
        val chooser = JFileChooser()
        chooser.dialogTitle = title
        if (chdirto != null) {
            chooser.currentDirectory = chdirto
        }
        val returnVal = chooser.showSaveDialog(GlobalOptions.uI)
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            filename = chooser.selectedFile.absolutePath
        }

        if (filename == null) {
            return null
        }

        if (File(filename).exists()) {
            val choix = arrayOf("Yes", "No")
            val resultat =
                JOptionPane.showOptionDialog(
                    null, "Overwrite $filename ?", "File Exist",
                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, choix,
                    choix[1]
                )
            if (resultat != 0) {
                return null
            }
        }
        return filename
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var buttonPanel: javax.swing.JPanel
    private lateinit var csvButton: javax.swing.JButton
    private lateinit var ctrlcButton: javax.swing.JButton
    private lateinit var graphPanel: javax.swing.JPanel
    private lateinit var jpgBuitton: javax.swing.JButton
    private lateinit var pngButton: javax.swing.JButton
    private lateinit var printButton: javax.swing.JButton
    // End of variables declaration//GEN-END:variables
    private var thegraph: Graph? = null
    private var mychartpanel: ChartPanel? = null

    companion object {
        private val log = LoggerFactory.getLogger(GraphView::class.java)
    }
}
