/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */

package net.atomique.ksar.ui

import java.awt.Component
import javax.swing.JCheckBox
import javax.swing.JPanel

class GraphSelection
/**
 * Creates new form GraphSelection
 */
    (parent: java.awt.Frame?, modal: Boolean, private val myview: DataView?) :
    javax.swing.JDialog(parent, modal) {

    init {
        initComponents()
        setLocationRelativeTo(parent)
        toFront()
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        jPanel1 = javax.swing.JPanel()
        jScrollPane1 = javax.swing.JScrollPane()
        jPanel3 = javax.swing.JPanel()
        jPanel2 = javax.swing.JPanel()
        selectallButton = javax.swing.JButton()
        unselectallButton = javax.swing.JButton()
        jSeparator2 = javax.swing.JSeparator()
        cancelButton = javax.swing.JButton()
        okButton = javax.swing.JButton()

        defaultCloseOperation = javax.swing.WindowConstants.DISPOSE_ON_CLOSE

        jPanel1.layout = java.awt.BorderLayout()

        jScrollPane1.preferredSize = java.awt.Dimension(300, 400)
        jScrollPane1.isRequestFocusEnabled = false

        jPanel3.layout = javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS)
        jScrollPane1.setViewportView(jPanel3)

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER)

        contentPane.add(jPanel1, java.awt.BorderLayout.CENTER)

        selectallButton.text = "Select All"
        selectallButton.addActionListener { evt -> selectallButtonActionPerformed(evt) }
        jPanel2.add(selectallButton)

        unselectallButton.text = "Unselect All"
        unselectallButton.addActionListener { evt -> unselectallButtonActionPerformed(evt) }
        jPanel2.add(unselectallButton)

        jSeparator2.orientation = javax.swing.SwingConstants.VERTICAL
        jPanel2.add(jSeparator2)

        cancelButton.text = "Cancel"
        cancelButton.addActionListener { evt -> cancelButtonActionPerformed(evt) }
        jPanel2.add(cancelButton)

        okButton.text = "Ok"
        okButton.addActionListener { evt -> okButtonActionPerformed(evt) }
        jPanel2.add(okButton)

        contentPane.add(jPanel2, java.awt.BorderLayout.SOUTH)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun cancelButtonActionPerformed(
        evt: java.awt.event.ActionEvent?
    ) { //GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose()
    } //GEN-LAST:event_cancelButtonActionPerformed

    private fun okButtonActionPerformed(
        evt: java.awt.event.ActionEvent?
    ) { //GEN-FIRST:event_okButtonActionPerformed
        this.dispose()
        OkforExport = true
    } //GEN-LAST:event_okButtonActionPerformed

    private fun selectallButtonActionPerformed(
        evt: java.awt.event.ActionEvent?
    ) { //GEN-FIRST:event_selectallButtonActionPerformed
        toggle_checkbox(jPanel3, true)
    } //GEN-LAST:event_selectallButtonActionPerformed

    private fun unselectallButtonActionPerformed(
        evt: java.awt.event.ActionEvent?
    ) { //GEN-FIRST:event_unselectallButtonActionPerformed
        toggle_checkbox(jPanel3, false)
    } //GEN-LAST:event_unselectallButtonActionPerformed

    fun toggle_checkbox(panel: JPanel, checked: Boolean) {
        val list = panel.components
        for (i in list.indices) {
            val tmp = list[i]
            if (tmp is JPanel) {
                toggle_checkbox(tmp, checked)
            }
            if (tmp is JCheckBox) {
                tmp.isSelected = checked
            }
        }
    }

    fun addPrintCheckBox(tmp: JCheckBox) {
        jPanel3.add(tmp)
        jPanel1.validate()
    }

    fun addPrintCheckBox(tmp: JPanel) {
        jPanel3.add(tmp)
        jPanel1.validate()
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var cancelButton: javax.swing.JButton
    private lateinit var jPanel1: javax.swing.JPanel
    private lateinit var jPanel2: javax.swing.JPanel
    private lateinit var jPanel3: javax.swing.JPanel
    private lateinit var jScrollPane1: javax.swing.JScrollPane
    private lateinit var jSeparator2: javax.swing.JSeparator
    private lateinit var okButton: javax.swing.JButton
    private lateinit var selectallButton: javax.swing.JButton
    private lateinit var unselectallButton: javax.swing.JButton
    // End of variables declaration//GEN-END:variables

    @JvmField
    var OkforExport = false
}
