/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */

package net.atomique.ksar.ui

import net.atomique.ksar.GlobalOptions
import net.atomique.ksar.xml.HostInfo

class HostInfoView
/**
 * Creates new form HostInfoView
 */
(parent: java.awt.Frame?, tmphostinfo: HostInfo) : javax.swing.JDialog(parent, true) {

    var hostinfo: HostInfo? = null

    init {
        hostinfo = tmphostinfo
        initComponents()
        Hostname.text = hostinfo!!.hostname
        AliasField.text = hostinfo!!.alias
        jTextArea1.text = hostinfo!!.description
        memboxcombo.setSelectedItem(hostinfo!!.memBlockSize.toString())
        setLocationRelativeTo(parent)
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @Suppress("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        jPanel1 = javax.swing.JPanel()
        hostnamePanel = javax.swing.JPanel()
        HostNameLabel = javax.swing.JLabel()
        Hostname = javax.swing.JLabel()
        AliasPanel = javax.swing.JPanel()
        AliasLabel = javax.swing.JLabel()
        AliasField = javax.swing.JTextField()
        DescriptionPanel = javax.swing.JPanel()
        descriptionLabel = javax.swing.JLabel()
        jScrollPane1 = javax.swing.JScrollPane()
        jTextArea1 = javax.swing.JTextArea()
        MemoryPanel = javax.swing.JPanel()
        memBlockSizeLabel = javax.swing.JLabel()
        memboxcombo = javax.swing.JComboBox<Any>()
        jPanel2 = javax.swing.JPanel()
        OkButton = javax.swing.JButton()

        defaultCloseOperation = javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE
        title = "Host Information"

        jPanel1.border = javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
        jPanel1.layout = javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS)

        hostnamePanel.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        HostNameLabel.labelFor = Hostname
        HostNameLabel.text = "Hostname:"
        hostnamePanel.add(HostNameLabel)

        Hostname.text = "hostname"
        hostnamePanel.add(Hostname)

        jPanel1.add(hostnamePanel)

        AliasPanel.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        AliasLabel.text = "Alias"
        AliasLabel.preferredSize = java.awt.Dimension(52, 14)
        AliasPanel.add(AliasLabel)

        AliasField.minimumSize = java.awt.Dimension(120, 20)
        AliasField.preferredSize = java.awt.Dimension(120, 20)
        AliasPanel.add(AliasField)

        jPanel1.add(AliasPanel)

        DescriptionPanel.layout =
            javax.swing.BoxLayout(DescriptionPanel, javax.swing.BoxLayout.PAGE_AXIS)

        descriptionLabel.text = "Description"
        descriptionLabel.preferredSize = java.awt.Dimension(52, 14)
        DescriptionPanel.add(descriptionLabel)

        jScrollPane1.preferredSize = java.awt.Dimension(300, 200)

        jTextArea1.columns = 20
        jTextArea1.rows = 5
        jTextArea1.preferredSize = java.awt.Dimension(300, 200)
        jScrollPane1.setViewportView(jTextArea1)

        DescriptionPanel.add(jScrollPane1)

        jPanel1.add(DescriptionPanel)

        MemoryPanel.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        memBlockSizeLabel.text = "Memory Block Size:"
        MemoryPanel.add(memBlockSizeLabel)

        memboxcombo.setModel(
            javax.swing.DefaultComboBoxModel(
                arrayOf<String>("1024", "2048", "4096", "8192", "16384")
            )
        )
        MemoryPanel.add(memboxcombo)

        jPanel1.add(MemoryPanel)

        contentPane.add(jPanel1, java.awt.BorderLayout.CENTER)

        jPanel2.layout = java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5)

        OkButton.text = "Ok"
        OkButton.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                OkButtonActionPerformed(evt)
            }
        })
        jPanel2.add(OkButton)

        contentPane.add(jPanel2, java.awt.BorderLayout.SOUTH)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun OkButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_OkButtonActionPerformed
        this.dispose()
        hostinfo!!.alias = AliasField.text
        hostinfo!!.description = jTextArea1.text
        hostinfo!!.setMemBlockSize(memboxcombo.selectedItem.toString())
        GlobalOptions.addHostInfo(hostinfo!!)
    } //GEN-LAST:event_OkButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var AliasField: javax.swing.JTextField
    private lateinit var AliasLabel: javax.swing.JLabel
    private lateinit var AliasPanel: javax.swing.JPanel
    private lateinit var DescriptionPanel: javax.swing.JPanel
    private lateinit var HostNameLabel: javax.swing.JLabel
    private lateinit var Hostname: javax.swing.JLabel
    private lateinit var MemoryPanel: javax.swing.JPanel
    private lateinit var OkButton: javax.swing.JButton
    private lateinit var descriptionLabel: javax.swing.JLabel
    private lateinit var hostnamePanel: javax.swing.JPanel
    private lateinit var jPanel1: javax.swing.JPanel
    private lateinit var jPanel2: javax.swing.JPanel
    private lateinit var jScrollPane1: javax.swing.JScrollPane
    private lateinit var jTextArea1: javax.swing.JTextArea
    private lateinit var memBlockSizeLabel: javax.swing.JLabel
    private lateinit var memboxcombo: javax.swing.JComboBox<Any>
    // End of variables declaration//GEN-END:variables
}
