/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */

package net.atomique.ksar.ui

import javax.swing.DefaultComboBoxModel

class LinuxDateFormat
/**
 * Creates new form LinuxDateFormat
 */
(parent: java.awt.Frame?, modal: Boolean) : javax.swing.JDialog(parent, modal) {

    private val LinuxFormatComboModel = DefaultComboBoxModel<Any>()
    private var ok_to_proceed = false

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var OkButton: javax.swing.JButton
    private lateinit var jCheckBox1: javax.swing.JCheckBox
    private lateinit var jComboBox1: javax.swing.JComboBox<Any>
    private lateinit var jLabel1: javax.swing.JLabel
    private lateinit var jPanel1: javax.swing.JPanel
    private lateinit var jPanel2: javax.swing.JPanel
    private lateinit var jPanel3: javax.swing.JPanel
    private lateinit var jPanel4: javax.swing.JPanel
    // End of variables declaration//GEN-END:variables

    init {
        initComponents()
        load_linuxformat()
        pack()
        setLocationRelativeTo(parent)
        toFront()
        isVisible = true
    }

    private fun load_linuxformat() {
        LinuxFormatComboModel.addElement("Automatic Detection")
        LinuxFormatComboModel.addElement("MM/DD/YY 23:59:59")
        LinuxFormatComboModel.addElement("MM/DD/YYYY 23:59:59")
        LinuxFormatComboModel.addElement("DD/MM/YY 23:59:59")
        LinuxFormatComboModel.addElement("DD/MM/YYYY 23:59:59")
        LinuxFormatComboModel.addElement("YYYY-MM-DD 23:59:59")
        LinuxFormatComboModel.addElement("MM/DD/YY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("MM/DD/YYYY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("DD/MM/YY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("DD/MM/YYYY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("YYYY-MM-DD 12:59:59 AM|PM")
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        jPanel1 = javax.swing.JPanel()
        jPanel3 = javax.swing.JPanel()
        jLabel1 = javax.swing.JLabel()
        jComboBox1 = javax.swing.JComboBox()
        jPanel4 = javax.swing.JPanel()
        jCheckBox1 = javax.swing.JCheckBox()
        jPanel2 = javax.swing.JPanel()
        OkButton = javax.swing.JButton()

        defaultCloseOperation = javax.swing.WindowConstants.DISPOSE_ON_CLOSE

        jPanel1.layout = javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS)

        jPanel3.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jLabel1.labelFor = jComboBox1
        jLabel1.text = "Select date format:"
        jPanel3.add(jLabel1)

        jComboBox1.model = LinuxFormatComboModel
        jComboBox1.preferredSize = java.awt.Dimension(300, 27)
        jPanel3.add(jComboBox1)

        jPanel1.add(jPanel3)

        jPanel4.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jCheckBox1.text = "Always use this format"
        jPanel4.add(jCheckBox1)

        jPanel1.add(jPanel4)

        contentPane.add(jPanel1, java.awt.BorderLayout.CENTER)

        OkButton.text = "Ok"
        OkButton.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                OkButtonActionPerformed(evt)
            }
        })
        jPanel2.add(OkButton)

        contentPane.add(jPanel2, java.awt.BorderLayout.SOUTH)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun OkButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_OkButtonActionPerformed
        this.dispose()
        ok_to_proceed = true
    } //GEN-LAST:event_OkButtonActionPerformed

    fun hasToRemenber(): Boolean {
        return jCheckBox1.isSelected
    }

    val dateFormat: String
        get() = jComboBox1.selectedItem as String

    val isOk: Boolean
        get() = ok_to_proceed
}
