/*
 * Copyright 2018 The kSAR Project. All rights reserved.
 * See the LICENSE file in the project root for more information.
 */

package net.atomique.ksar.ui

import net.atomique.ksar.Config
import net.atomique.ksar.GlobalOptions
import javax.swing.DefaultComboBoxModel
import javax.swing.JComboBox
import javax.swing.SpinnerNumberModel
import javax.swing.SwingUtilities
import javax.swing.UIManager

class Preferences
/**
 * Creates new form Preferences
 */
(parent: java.awt.Frame?) : javax.swing.JDialog(parent) {

    private fun load_landf() {
        val looks = UIManager.getInstalledLookAndFeels()
        var i = 0
        val n = looks.size
        while (i < n) {
            val tmp = looks[i].name
            UI_lanf_model.addElement(tmp)
            if (Config.landf == tmp) {
                jComboBox1.selectedItem = tmp
            }
            i++
        }
    }

    private fun load_linuxformat() {
        LinuxFormatComboModel.addElement("Automatic Detection")
        LinuxFormatComboModel.addElement("Always ask")
        LinuxFormatComboModel.addElement("MM/DD/YY 23:59:59")
        LinuxFormatComboModel.addElement("MM/DD/YYYY 23:59:59")
        LinuxFormatComboModel.addElement("DD/MM/YY 23:59:59")
        LinuxFormatComboModel.addElement("DD/MM/YYYY 23:59:59")
        LinuxFormatComboModel.addElement("YYYY-MM-DD 23:59:59")
        LinuxFormatComboModel.addElement("MM/DD/YY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("MM/DD/YYYY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("DD/MM/YY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("DD/MM/YYYY 12:59:59 AM|PM")
        LinuxFormatComboModel.addElement("YYYY-MM-DD 12:59:59 AM|PM")

        jComboBox3.selectedItem = Config.linuxDateFormat
    }

    private fun load_pageformat() {
        PageFormatComboBox.addElement("A4")
        PageFormatComboBox.addElement("LETTER")
        PageFormatComboBox.addElement("LEGAL")
        jComboBox2.selectedItem = Config.pDFPageFormat
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @Suppress("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {

        jPanel1 = javax.swing.JPanel()
        jScrollPane1 = javax.swing.JScrollPane()
        jPanel4 = javax.swing.JPanel()
        jPanel5 = javax.swing.JPanel()
        jLabel1 = javax.swing.JLabel()
        jComboBox1 = javax.swing.JComboBox()
        jPanel10 = javax.swing.JPanel()
        jLabel7 = javax.swing.JLabel()
        jComboBox3 = javax.swing.JComboBox()
        jPanel6 = javax.swing.JPanel()
        jLabel2 = javax.swing.JLabel()
        jPanel8 = javax.swing.JPanel()
        jLabel5 = javax.swing.JLabel()
        jPanel7 = javax.swing.JPanel()
        jLabel3 = javax.swing.JLabel()
        jSpinner1 = javax.swing.JSpinner()
        jLabel4 = javax.swing.JLabel()
        jSpinner2 = javax.swing.JSpinner()
        jPanel9 = javax.swing.JPanel()
        jLabel6 = javax.swing.JLabel()
        jComboBox2 = javax.swing.JComboBox()
        jPanel3 = javax.swing.JPanel()
        jPanel2 = javax.swing.JPanel()
        OkButton = javax.swing.JButton()
        CancelButton = javax.swing.JButton()

        defaultCloseOperation = javax.swing.WindowConstants.DISPOSE_ON_CLOSE

        jPanel1.preferredSize = java.awt.Dimension(430, 430)
        jPanel1.layout = java.awt.BorderLayout()

        jPanel4.layout = javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS)

        jPanel5.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jLabel1.text = "Look and Feel: "
        jPanel5.add(jLabel1)

        jComboBox1.model = UI_lanf_model
        jComboBox1.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                jComboBox1ActionPerformed(evt)
            }
        })
        jPanel5.add(jComboBox1)

        jPanel4.add(jPanel5)

        jPanel10.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jLabel7.labelFor = jComboBox3
        jLabel7.text = "Linux Format:"
        jPanel10.add(jLabel7)

        jComboBox3.model = LinuxFormatComboModel
        jPanel10.add(jComboBox3)

        jPanel4.add(jPanel10)

        jPanel6.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2)

        jLabel2.text = "Language: "
        jPanel6.add(jLabel2)

        jPanel4.add(jPanel6)

        jPanel8.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jLabel5.text = "JPG/PNG"
        jPanel8.add(jLabel5)

        jPanel7.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jLabel3.text = "Width:"
        jPanel7.add(jLabel3)

        jSpinner1.model = imageWidthSpinner
        jSpinner1.minimumSize = java.awt.Dimension(80, 28)
        jSpinner1.preferredSize = java.awt.Dimension(80, 28)
        jSpinner1.value = 800
        jPanel7.add(jSpinner1)

        jLabel4.text = "Height:"
        jPanel7.add(jLabel4)

        jSpinner2.model = imageHeightSpinner
        jSpinner2.minimumSize = java.awt.Dimension(80, 28)
        jSpinner2.preferredSize = java.awt.Dimension(80, 28)
        jPanel7.add(jSpinner2)

        jPanel8.add(jPanel7)

        jPanel4.add(jPanel8)

        jPanel9.layout = java.awt.FlowLayout(java.awt.FlowLayout.LEFT)

        jLabel6.text = "PDF Page Format:"
        jPanel9.add(jLabel6)

        jComboBox2.model = PageFormatComboBox
        jComboBox2.minimumSize = java.awt.Dimension(100, 27)
        jComboBox2.preferredSize = java.awt.Dimension(100, 27)
        jPanel9.add(jComboBox2)

        jPanel4.add(jPanel9)

        jScrollPane1.setViewportView(jPanel4)

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.NORTH)

        jPanel2.layout = javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS)

        OkButton.text = "Ok"
        OkButton.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                OkButtonActionPerformed(evt)
            }
        })
        jPanel2.add(OkButton)

        CancelButton.text = "Cancel"
        CancelButton.addActionListener(object : java.awt.event.ActionListener {
            override fun actionPerformed(evt: java.awt.event.ActionEvent) {
                CancelButtonActionPerformed(evt)
            }
        })
        jPanel2.add(CancelButton)

        jPanel3.add(jPanel2)

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END)

        contentPane.add(jPanel1, java.awt.BorderLayout.CENTER)

        pack()
    } // </editor-fold>//GEN-END:initComponents

    private fun jComboBox1ActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_jComboBox1ActionPerformed
        val source = evt.source
        var lafClassName: String? = null
        if (source === jComboBox1) {
            val comboBox = source as JComboBox<*>
            lafClassName = comboBox.selectedItem as String?
            if (lafClassName != null) {
                //String finalLafClassName = lafClassName;
                for (laf in UIManager.getInstalledLookAndFeels()) {
                    if (lafClassName == laf.name) {
                        try {
                            UIManager.setLookAndFeel(laf.className)
                            SwingUtilities.updateComponentTreeUI(GlobalOptions.uI)
                        } catch (e: Exception) {
                        }
                    }
                }
            }
        }
    } //GEN-LAST:event_jComboBox1ActionPerformed

    private fun OkButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_OkButtonActionPerformed
        Config.landf = jComboBox1.selectedItem.toString()
        Config.pDFPageFormat = jComboBox2.selectedItem.toString()
        Config.imageHeight = jSpinner2.model.value as Int
        Config.imageWidth = jSpinner1.model.value as Int
        Config.linuxDateFormat = jComboBox3.selectedItem.toString()
        Config.save()
        dispose()
    } //GEN-LAST:event_OkButtonActionPerformed

    private fun CancelButtonActionPerformed(
        evt: java.awt.event.ActionEvent
    ) { //GEN-FIRST:event_CancelButtonActionPerformed
        dispose()
    } //GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var CancelButton: javax.swing.JButton
    private lateinit var OkButton: javax.swing.JButton
    private lateinit var jComboBox1: javax.swing.JComboBox<Any>
    private lateinit var jComboBox2: javax.swing.JComboBox<Any>
    private lateinit var jComboBox3: javax.swing.JComboBox<Any>
    private lateinit var jLabel1: javax.swing.JLabel
    private lateinit var jLabel2: javax.swing.JLabel
    private lateinit var jLabel3: javax.swing.JLabel
    private lateinit var jLabel4: javax.swing.JLabel
    private lateinit var jLabel5: javax.swing.JLabel
    private lateinit var jLabel6: javax.swing.JLabel
    private lateinit var jLabel7: javax.swing.JLabel
    private lateinit var jPanel1: javax.swing.JPanel
    private lateinit var jPanel10: javax.swing.JPanel
    private lateinit var jPanel2: javax.swing.JPanel
    private lateinit var jPanel3: javax.swing.JPanel
    private lateinit var jPanel4: javax.swing.JPanel
    private lateinit var jPanel5: javax.swing.JPanel
    private lateinit var jPanel6: javax.swing.JPanel
    private lateinit var jPanel7: javax.swing.JPanel
    private lateinit var jPanel8: javax.swing.JPanel
    private lateinit var jPanel9: javax.swing.JPanel
    private lateinit var jScrollPane1: javax.swing.JScrollPane
    private lateinit var jSpinner1: javax.swing.JSpinner
    private lateinit var jSpinner2: javax.swing.JSpinner
    // End of variables declaration//GEN-END:variables
    var UI_lanf_model = DefaultComboBoxModel<Any>()
    var PageFormatComboBox = DefaultComboBoxModel<Any>()
    var LinuxFormatComboModel = DefaultComboBoxModel<Any>()
    var imageWidthSpinner =
        javax.swing.SpinnerNumberModel(Config.imageWidth, 1, null, 1)
    var imageHeightSpinner =
        javax.swing.SpinnerNumberModel(Config.imageHeight, 1, null, 1)

    init {
        initComponents()
        load_landf()
        load_pageformat()
        load_linuxformat()
        setLocationRelativeTo(parent)
        isModal = true
        isVisible = true
    }
}
