name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk17
          arguments: --scan --no-parallel --no-daemon -Prelease build
      - name: Prepare GitHub Release
        id: prepare_release
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Attach files to release
        uses: actions/github-script@v7
        env:
          TAG: ${{ github.ref_name }}
          # https://github.com/release-drafter/release-drafter#action-outputs
          RELEASE_ID: ${{ steps.prepare_release.outputs.id }}
        with:
          # language=JavaScript
          script: |
            const fs = require('fs');
            const {TAG, RELEASE_ID} = process.env;
            // remove old jar files from the release
            const assets = await github.rest.repos.listReleaseAssets({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: RELEASE_ID
            });
            for (const asset of assets.data) {
                if (asset.name.endsWith('-all.jar')) {
                    await github.rest.repos.deleteReleaseAsset({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        asset_id: asset.id
                    });
                }
            }
            const version = TAG.substring(1); // remove leading v
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "ksar-" + version + ".jar",
              release_id: RELEASE_ID,
              data: fs.readFileSync("build/libs/ksar-" + version +  "-all.jar")
            })
      - name: Publish GitHub Release
        id: publish_release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
